### ISSUE TITLE
Home Assistant Warning since updating to 2022.3.8

### ISSUE THREAD

**Issue by sparment** [gogades/hass-infinitive#12]
Since updating to 2022.3.8 I see the following warning in the log at boot-up:

Entity climate.infinitive (<class 'custom_components.infinitive.climate.InfinitiveDevice'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by mww012** [comment]
Thanks for the heads up!

Looks like we just need to rename device_state_attributes to extra_device_attributes. I'll work on that this week.

**Comment by mww012** [comment]
Corrected in v0.0.9
