### ISSUE TITLE
Changes with 2024.1.0 showing warnings

### ISSUE THREAD

**Issue by sparment** [gogades/hass-infinitive#16]
Looks like the new climate changes with HA 2024.1.0 are throwing some warnings about deprecated elements that will be removed with 2025.1.

@mww012 please let me know if I can be any help with code change testing!

Logger: homeassistant.const
Source: helpers/deprecation.py:204
TEMP_FAHRENHEIT was used from infinitive, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.FAHRENHEIT instead, please report it to the author of the 'infinitive' custom integration

Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:204
CURRENT_HVAC_IDLE was used from infinitive, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please report it to the author of the 'infinitive' custom integration
SUPPORT_TARGET_TEMPERATURE was used from infinitive, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'infinitive' custom integration
SUPPORT_TARGET_TEMPERATURE_RANGE was used from infinitive, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE_RANGE instead, please report it to the author of the 'infinitive' custom integration
SUPPORT_FAN_MODE was used from infinitive, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'infinitive' custom integration
SUPPORT_PRESET_MODE was used from infinitive, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'infinitive' custom integration

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1520
Entity None (<class 'custom_components.infinitive.climate.InfinitiveDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|FAN_MODE|PRESET_MODE: 25>, please report it to the author of the 'infinitive' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by gogades** [comment]
I have a fix in progress for this.

**Comment by sparment** [comment]
@gogades  any update on this?

**Comment by gogades** [comment]
@sparment [confirmed ](https://github.com/gogades/hass-infinitive/pull/19#issuecomment-2537489531) this issue now resolved. Closing.
