### ISSUE TITLE
Trouble with installation via HACS

### ISSUE THREAD

**Issue by sparment** [gogades/hass-infinitive#2]
@mww012 I'm moving my custom integrations over to HACS and am having an issue getting infinitive installed. I go to add a custom repository and paste in "https://github.com/mww012/hass-infinitive.git" and select "integration" as the category; but I get the following error:

GitHub returned 404 for https://api.github.com/repos/mww012/hass-infinitive.git

I double check multiple times that I pasted in the correct repository but keep getting this error. Is this something on the infinitive side of things that you can help me with?

**Comment by mww012** [comment]
@sparment Hey, I tried and got the same error you did.  I don't know if HACS has changed their procedure or if something happened to my repo.  I haven't changed anything on my end but I'll figure it out and let you know.

**Comment by mww012** [comment]
@sparment Try this.  Drop the ".git" from the end of the URL.  So your actual URL will be `https://github.com/mww012/hass-infinitive`.  That fixed things for me.  If it works for you I'll update the docs and correct it.

**Comment by sparment** [comment]
Thanks, that did the trick for me!
