### ISSUE TITLE
Home Assistant warning there is no 'version' key

### ISSUE THREAD

**Issue by CrispyPyro** [gogades/hass-infinitive#6]
Home Assistant logs have the following warning:

Logger: homeassistant.loader
Source: loader.py:794

No 'version' key in the manifest file for custom integration 'infinitive'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'infinitive'

**Comment by mww012** [comment]
Hey, sorry I haven't gotten to this before now.  Life's been a little busy.  I'm working on getting this fixed.

**Comment by mww012** [comment]
I believe this is fixed now.  Let me know if you're still seeing this issue.
