### ISSUE TITLE
Weird values + fan control

### ISSUE THREAD

**Issue by trailsurfer604** [gogades/hass-infinitive#7]
Hi,

I have Infinitive running on a Raspberry Pi, talking to my Carrier system, I've successfully installed HACS and the Infinitive integration for HA, and climate.infinitive entity shows up.

I have two issues with entity:

1. I am getting weird temperature values

Here is what I am getting from entity settings:
![image](https://user-images.githubusercontent.com/75198746/129840247-b7ceb62d-74ca-474a-a8fa-ba8d77426542.png)

Here is what Infinitive UI shows:

![image](https://user-images.githubusercontent.com/75198746/129840272-a01d6116-de3b-4025-b2fe-40fac00f00e9.png)

2. I've added the thermostat card to the Lovelace UI, but it doesn't seem to do anything (changing values doesn't change anything on the thermostat or on the Infinitive UI, there is no outside temp displayed, and I can't see how I can control the fan.

![image](https://user-images.githubusercontent.com/75198746/129840455-cc55b2c1-d67d-4d21-bc85-206f265f9cbb.png)

What am I missing?

**Comment by mangusman07** [comment]
24f is -4.44c. are you sure you don't have a config in HA that is re-converting your celcius values from infinitive into celcius again?

**Comment by trailsurfer604** [comment]
If I do, I have no idea where and why it would be.  My Tesla’s temps are reported correctly.

**Comment by mww012** [comment]
I bet that's what is happening. Somehow HA is doing the conversion from F to C twice.

72F is 22.22C
22.22F is -5.43C

That's right around the numbers you're seeing. I'll see if I can dig into this tomorrow. Hopefully it'll be an easy fix.

**Comment by trailsurfer604** [comment]
Hey, did you ever get a chance to dig into this?

**Comment by trailsurfer604** [comment]
I fixed it.

Clymate.py is hard set to TEMP_FAHRENHEIT.  Changing that to TEMP_CELSIUS fixes the issue.

This should either be a manual setting for the entity to match how Infinitive is configured, or should pull this directly from infinitive.  Barring that should probably must mention it in the instructions for the Canucks among us lol.

**Comment by mww012** [comment]
Hey bud.  Sorry I've been absent lately.  I'm glad you found the root of your issue. I'll try to take a look and see if there's a better way to handle the temp units than statically setting it.
